### ISSUE TITLE
支持默认打开的页面为暗黑模式吧

### ISSUE THREAD

**Issue by hantmac** [niudai/VSCode-Zhihu#1]
支持默认打开的页面为暗黑模式吧，不然上班不太好摸鱼🤔

**Comment by niudai** [comment]
目前主要考量是页面风格和知乎Web端保持统一, 不过这个可以作为配置项在未来的版本加入

**Comment by hantmac** [comment]
> 目前主要考量是页面风格和知乎Web端保持统一, 不过这个可以作为配置项在未来的版本加入

跟随vscode主题能做到的话也会很棒（我不太懂，不知道好不好做）

**Comment by niudai** [comment]
already implemented in 0.2.0, please check.
