### ISSUE TITLE
建议添加专栏管理

### ISSUE THREAD

**Issue by GGorun** [niudai/VSCode-Zhihu#10]
希望能够对专栏进行管理，这样就可以
**只用VSCode搞定一切！**
万分感谢：)

**Comment by GGorun** [comment]
还希望可以添加赞同&喜欢等功能：)

**Comment by niudai** [comment]
专栏管理有的  赞同喜欢也可以加入  后续版本会逐渐增加

**Comment by niudai** [comment]
已经实现，赞同 + 专栏管理。
