### ISSUE TITLE
B站专栏大佬要不要考虑支持一下？

### ISSUE THREAD

**Issue by Uzizkp** [niudai/VSCode-Zhihu#100]
B站专栏也是富文本编辑器，是不是和知乎的情况差不多？能不能也支持一下

**Comment by niudai** [comment]
最终目标是支持所有主流平台，但是我太忙了，没时间搞，唉



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 黑鲸 ***@***.***&gt;
发送时间: 2021年7月5日 02:12
收件人: niudai/VSCode-Zhihu ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[niudai/VSCode-Zhihu] B站专栏大佬要不要考虑支持一下？ (#100)





 
B站专栏也是富文本编辑器，是不是和知乎的情况差不多？能不能也支持一下
