### ISSUE TITLE
MarkDown中图片链接不支持空格

### ISSUE THREAD

**Issue by zezhishao** [niudai/VSCode-Zhihu#105]
您好！
今天试用了一下您的插件，非常好用，但是发现了一个bug～
MarkDown中图片链接不支持空格，Preview可以，但是发布就会显示图片链接异常！

**Comment by niudai** [comment]
好的，完了修复一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: S22 ***@***.***&gt;
发送时间: 2021年8月18日 11:39
收件人: niudai/VSCode-Zhihu ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[niudai/VSCode-Zhihu] MarkDown中图片链接不支持空格 (#105)





 
您好！
 今天试用了一下您的插件，非常好用，但是发现了一个bug～
 MarkDown中图片链接不支持空格，Preview可以，但是发布就会显示图片链接异常！
