### ISSUE TITLE
建议增加自动获取外链图片并上传

### ISSUE THREAD

**Issue by zhaoxf4** [niudai/VSCode-Zhihu#11]
大佬好，我有个不知道算不算小众的需求场景：文章之前发在其它平台上或自己博客上，图片在其他平台或图床上，想转移到知乎，可以直接检测下载外链图片并上传到知乎，替换成知乎的图片链接。想问一下大佬或者其他人有没有什么思路？

**Comment by niudai** [comment]
我这个支持一个从粘贴板复制图片的功能，把图片复制一下就能直接上传



---原始邮件---
发件人: "zhaoxf4"<notifications@github.com&gt;
发送时间: 2020年2月18日(周二) 下午5:16
收件人: "niudai/VSCode-Zhihu"<VSCode-Zhihu@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [niudai/VSCode-Zhihu] 建议增加自动获取外链图片并上传 (#11)



大佬好，我有个不知道算不算小众的需求场景：文章之前发在其它平台上或自己博客上，图片在其他平台或图床上，想转移到知乎，可以直接检测下载外链图片并上传到知乎，替换成知乎的图片链接。想问一下大佬或者其他人有没有什么思路？
