### ISSUE TITLE
第一次下载安装，没有"Zhihu:Preview"按钮。

### ISSUE THREAD

**Issue by jonasjunzhang** [niudai/VSCode-Zhihu#116]
点击VSCode自带的Markdown Preview按钮，显示的是VSCode原版主题，无法显示知乎主题。
配置项Zhihu: Use VSTheme已勾选。

**Comment by jungle-gym-ac** [comment]
点击VSCode自带的Markdown Preview按钮，显示的是VSCode原版主题，无法显示知乎主题。
配置项Zhihu: Use VSTheme已勾选。

**Comment by niudai** [comment]
这个功能下掉了，直接用自带的 markdown preview 就行
