### ISSUE TITLE
登陆不支持邮箱，也不支持国外手机号

### ISSUE THREAD

**Issue by weiyicheng** [niudai/VSCode-Zhihu#12]
这里：
		let loginData: ILogin = {
			'client_id': 'c3cef7c66a1843f8b3a9e6a1e3160e20',
			'grant_type': 'password',
			'source': 'com.zhihu.web',
			'username': '+86' + phoneNumber,
			'password': password,
			'lang': 'en',
			'ref_source': 'homepage',
			'utm_source': '',
			'captcha': captcha,
			'timestamp': Math.round(new Date().getTime()),
			'signature': ''
		};

**Comment by niudai** [comment]
我知道，但是基本上大家都用二维码登录，所以暂时先不管

**Comment by liuxilu** [comment]
给我捐个手机吧……

**Comment by liuxilu** [comment]
（逃

**Comment by liuxilu** [comment]
密码登录403了
