### ISSUE TITLE
打不开webview了

### ISSUE THREAD

**Issue by trotsky1997** [niudai/VSCode-Zhihu#122]
TypeError: Cannot read property 'map' of undefined

**Comment by Mashiirox** [comment]
i have the same problem

**Comment by CWenTeng** [comment]
i have the same problem to
[exthost] [error] TypeError: Cannot read property 'map' of undefined
(niudai.vscode-zhihu-0.5.0\dist\extension.js:2:2467742) zhihu.openWebView undefined

**Comment by niudai** [comment]
让我看看

**Comment by zhangwenr** [comment]
遇到了同样的问题，点击条目，VSCode知乎页面无法打开

**Comment by James-chok** [comment]
是知乎的反爬虫机制吗？

**Comment by zhangcj13** [comment]
基本不跳转，偶尔一次能打开，有人解决了吗

**Comment by Kevin9703** [comment]
我也遇到这个问题了
命令"Zhihu: openWebView"导致错误 (Cannot read property 'type' of undefined)

**Comment by xqtbox** [comment]
同问，左侧能看到题目，点击后，右侧不显示具体内容，没反应

**Comment by jeffatoptics** [comment]
+1

**Comment by lmhtolin** [comment]
+1

**Comment by decradish** [comment]
看来作者把这个事给忘记了~

**Comment by heartacker** [comment]
@niudai

**Comment by likelyzhao** [comment]
+ 1

**Comment by niudai** [comment]
已经解决。

**Comment by heartacker** [comment]
@niudai 是否可以添加一些maintainer， 这个项目看起来就像没人维护一样啊

**Comment by niudai** [comment]
ok



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: heartacker ***@***.***&gt;
发送时间: 2022年7月3日 21:47
收件人: niudai/VSCode-Zhihu ***@***.***&gt;
抄送: DaiNiu ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [niudai/VSCode-Zhihu] 打不开webview了 (Issue #122)





 
@niudai 是否可以添加一些maintainer， 这个项目看起来就像没人维护一样啊
