### ISSUE TITLE
markdown换行

### ISSUE THREAD

**Issue by fire-lit-band** [niudai/VSCode-Zhihu#127]
我发现我的markdown发布的时候，所有的字符都黏在一起（压根没有换行），能不能增加一个发布的时候自动换行的功能（我自己的vscode在预览markdown，是可以自己自动换行的，而不用手动加入换行）

**Comment by shouldsee** [comment]
各个markdown的语法不同,建议每次新开段落双回车即可. 不建议在插件内部加上非必要的自动变换,因为这样会削弱插件的表达能力.建议通过修改md源直接达成需要的格式.

```md
This is first paragraph

This is second paragraph
```

**Comment by niudai** [comment]
参考 @shouldsee 的方法即可。
