### ISSUE TITLE
如何参与贡献？使用 npm install 后仍报错无法参与开发

### ISSUE THREAD

**Issue by OrangeX4** [niudai/VSCode-Zhihu#128]
我 fork 了一份代码，并 clone 到了本地，尝试加上一点我需要的功能。

但是在我 `npm install` 了之后，执行 F5 后依然报错，无法正常调试。

如图所示：

https://gitee.com/orangex4/picgo/raw/master/images/20220222224953.png

![图片](https://gitee.com/orangex4/picgo/raw/master/images/20220222224953.png)

我的开发环境是 Kubuntu，但我在 Windows 下也尝试运行，依然报相同的错。

报错如下:

```json
// Error: the description can't be converted into a problem matcher:
{
    "base": "$ts-webpack-watch",
    "background": {
        "activeOnStart": true,
        "beginsPattern": "webpack is watching the files…",
        "endsPattern": "^Built at: .* [AP]M"
    }
}
```

**Comment by James-chok** [comment]
看一下 [`CONTRIBUTING.md`](https://github.com/niudai/VSCode-Zhihu/blob/master/CONTRIBUTING.md)

**Comment by OrangeX4** [comment]
感谢，之前一直没注意到 : - (
