### ISSUE TITLE
多行公式（align）出现多余<br>

### ISSUE THREAD

**Issue by wu5bocheng** [niudai/VSCode-Zhihu#131]
## Example:
```
$$
\begin{aligned}

P(x) &= \int P(x \mid \mu) P(\mu) d\mu\\
&=\int_{-\infty}^{\infty} \frac{1}{\sigma \sqrt{2 \pi}} e^{-\frac{1}{2}\left(\frac{x-\mu}{\sigma}\right)^{2}}\frac{1}{b \sqrt{2 \pi}} e^{-\frac{1}{2}\left(\frac{\mu-a}{b}\right)^{2}} d\mu\\
&=\frac{1}{2 \sigma b \pi}\int_{-\infty}^{\infty} e^{-\frac{1}{2}\frac{(x-\mu)^2b^2+(\mu-a)^2\sigma^2}{\sigma^2 b^2}} d\mu\\
&=\frac{1}{2 \sigma b \pi}\int_{-\infty}^{\infty}exp\left(-\frac{1}{2}\left(\frac{\left(\mu-\frac{xb^2+a\sigma^2}{\sigma^2+b^2}\right)^2}{\frac{\sigma^2b^2}{\sigma^2+b^2}}+\frac{(x-a)^2}{\sigma^2+b^2}\right)\right)d\mu\\
&=\frac{e^{-\frac{1}{2}\frac{(x-a)^2}{\sigma^2+b^2}}}{2 \sigma b \pi}\frac{\sigma b}{\sqrt{\sigma^2+b^2}}\sqrt{2 \pi}\int_{-\infty}^{\infty}\frac{1}{\frac{\sigma b}{\sqrt{\sigma^2+b^2}}\sqrt{2 \pi}}exp\left(-\frac{1}{2}\left(\frac{\left(\mu-\frac{xb^2+a\sigma^2}{\sigma^2+b^2}\right)^2}{\frac{\sigma^2b^2}{\sigma^2+b^2}}\right)\right)d\mu\\
&=\frac{1}{\sqrt{\sigma^2+b^2}\sqrt{2 \pi}}e^{-\frac{1}{2}\frac{(x-a)^2}{\sigma^2+b^2}}\int_{-\infty}^{\infty} \mu\sim N\left(\frac{xb^2+a\sigma^2}{\sigma^2+b^2},\frac{\sigma b}{\sqrt{\sigma^2+b^2}}\right)d\mu\\
&=\frac{1}{\sqrt{\sigma^2+b^2}\sqrt{2 \pi}}e^{-\frac{1}{2}\frac{(x-a)^2}{\sigma^2+b^2}}

\end{aligned}
$$
```
## Result:
![image](https://user-images.githubusercontent.com/79819545/159158753-d2c5cf45-2ec1-447c-8f12-efd285dd95df.png)

## Try:
通过正则匹配将align中所有内容合并为一行，可以解决问题

**Comment by wu5bocheng** [comment]
尝试解决方法：
正则替换
\n\\end\{aligned\}--->\end{aligned}
\\begin\{aligned\}\n--->\begin{aligned}
\\\n-->\\
建议先匹配两个{align}标签之间的部分，再运用正则替换，以免出现恶性bug

**Comment by shouldsee** [comment]
无法复现. https://zhuanlan.zhihu.com/p/517507882

**Comment by shouldsee** [comment]
好像可以复现了,混用align和非align时似乎会出现,复现不是很稳定

```
$$
x=1\\
y=2
$$

$$\begin{align}
x=1\\
y=2
\end{align}$$
```

**Comment by wu5bocheng** [comment]
很可惜，作者已经放弃更新该项目了，所以bug应该是木有办法了

**Comment by ZUIcat** [comment]
我也有过这个问题，然后我检查了下我的换行的` \\`前有个空格，然后我把空格删了变成`\\`就好了……

**Comment by shouldsee** [comment]
> 我也有过这个问题，然后我检查了下我的换行的` \\`前有个空格，然后我把空格删了变成`\\`就好了……

说实话我目前还是不能稳定复现这个问题,谁要是碰上了可以提供个example latex code试试

**Comment by shouldsee** [comment]
目前找到办法复现了:

把上述markdown代码通过vscode-zhihu发布到知乎,显示正常

打开知乎网页编辑器编辑文章,保存

这个时候公式里多出了<br>

要临时解决这个问题,很简单,只要用插件重新发布一遍,覆盖zhihu上的文章就可以.缺点是无法在zhihu里做比较复杂的编辑.不过重新发布的时候,zhihu那边的元数据一般是会保留的

**Comment by TangJiakai** [comment]
发布完之后 不要把最下面的 本文使用 [Zhihu On VSCode]创作并发布 去掉就好

**Comment by shouldsee** [comment]
> 发布完之后 不要把最下面的 本文使用 [Zhihu On VSCode]创作并发布 去掉就好

恩,因为如果用知乎编辑器操作过并保存,就会触发这个问题.具体机制还不是很清楚

----

事实上，如果尝试去除文字，肯定要在知乎里编辑保存一下，就必然出问题。 所以并不是对水印文字敏感，是对知乎编辑器的保存敏感
