### ISSUE TITLE
latex 公式颜色渲染，知乎显示不正常

### ISSUE THREAD

**Issue by BottomCoder-Ander** [niudai/VSCode-Zhihu#141]
公式
```
$$L = \left[\begin{aligned} 
    &1{\color{red}[0,0,0,0]} \\
    &2{\color{red}[0,1,0,0]} \\
    &3{\color{red}[1,1,0,1]} \\ 
    &4{\color{red}[1,2,0,0]} \\
    &5{\color{red}[2,2,0,0]} \\
    &6{\color{green}[2,2,0,1]} \\
    &7{\color{red}[3,3,0,2]} \\ 
    &8{\color{red}[3,3,1,2]} \\
    &9{\color{red}[4,3,1,2]} 
    \end{aligned}
    \right]\\$$
```

本地
![image](https://user-images.githubusercontent.com/68366578/168841079-89b94557-dee4-4c18-af64-e6f67eb011fb.png)

知乎
![image](https://user-images.githubusercontent.com/68366578/168841167-7da27eca-7515-4af1-b3b3-be3778f58af0.png)

知乎上只渲染了一个括号？怎么回事。是知乎的bug吗

**Comment by shouldsee** [comment]
估计本地的vscode md latex渲染和zhihu后端的latex渲染不同. 按照latex严格语法即可

```latex
$$
L = \left[\begin{aligned} 
    &1{\color{red}{ [0,0,0,0]} }  \\  %% 括号
    &2{\color{red}[0,1,0,0]} \\
    &3{\color{red}[1,1,0,1]} \\ 
    &4{\color{red}[1,2,0,0]} \\
    &5{\color{red}[2,2,0,0]} \\
    &6{\color{green}[2,2,0,1]} \\
    &7{\color{red}[3,3,0,2]} \\ 
    &8{\color{red}[3,3,1,2]} \\
    &9{\color{red}[4,3,1,2]} 
    \end{aligned}
    \right]\\
$$
```

![img](https://www.zhihu.com/equation?tex=L+%3D+%5Cleft%5B%5Cbegin%7Baligned%7D+%0A++++%261%7B%5Ccolor%7Bred%7D%7B+%5B0%2C0%2C0%2C0%5D%7D+%7D++%5C%5C%0A++++%262%7B%5Ccolor%7Bred%7D%5B0%2C1%2C0%2C0%5D%7D+%5C%5C%0A++++%263%7B%5Ccolor%7Bred%7D%5B1%2C1%2C0%2C1%5D%7D+%5C%5C+%0A++++%264%7B%5Ccolor%7Bred%7D%5B1%2C2%2C0%2C0%5D%7D+%5C%5C%0A++++%265%7B%5Ccolor%7Bred%7D%5B2%2C2%2C0%2C0%5D%7D+%5C%5C%0A++++%266%7B%5Ccolor%7Bgreen%7D%5B2%2C2%2C0%2C1%5D%7D+%5C%5C%0A++++%267%7B%5Ccolor%7Bred%7D%5B3%2C3%2C0%2C2%5D%7D+%5C%5C+%0A++++%268%7B%5Ccolor%7Bred%7D%5B3%2C3%2C1%2C2%5D%7D+%5C%5C%0A++++%269%7B%5Ccolor%7Bred%7D%5B4%2C3%2C1%2C2%5D%7D+%0A++++%5Cend%7Baligned%7D%0A++++%5Cright%5D%5C%5C)

建议close

**Comment by BottomCoder-Ander** [comment]
> 估计本地的vscode md latex渲染和zhihu后端的latex渲染不同. 按照latex严格语法即可
> 
> ```
> $$
> L = \left[\begin{aligned} 
>     &1{\color{red}{ [0,0,0,0]} }  \\  %% 括号
>     &2{\color{red}[0,1,0,0]} \\
>     &3{\color{red}[1,1,0,1]} \\ 
>     &4{\color{red}[1,2,0,0]} \\
>     &5{\color{red}[2,2,0,0]} \\
>     &6{\color{green}[2,2,0,1]} \\
>     &7{\color{red}[3,3,0,2]} \\ 
>     &8{\color{red}[3,3,1,2]} \\
>     &9{\color{red}[4,3,1,2]} 
>     \end{aligned}
>     \right]\\
> $$
> ```
> 
> ![img](https://camo.githubusercontent.com/cae3256a85cc267962237dd70a4aef89d9bdd9997d72a7590605983bfba197ca/68747470733a2f2f7777772e7a686968752e636f6d2f6571756174696f6e3f7465783d4c2b2533442b2535436c656674253542253543626567696e253742616c69676e65642537442b2530412b2b2b2b25323631253742253543636f6c6f722537427265642537442537422b253542302532433025324330253243302535442537442b2537442b2b2535432535432530412b2b2b2b25323632253742253543636f6c6f72253742726564253744253542302532433125324330253243302535442537442b2535432535432530412b2b2b2b25323633253742253543636f6c6f72253742726564253744253542312532433125324330253243312535442537442b2535432535432b2530412b2b2b2b25323634253742253543636f6c6f72253742726564253744253542312532433225324330253243302535442537442b2535432535432530412b2b2b2b25323635253742253543636f6c6f72253742726564253744253542322532433225324330253243302535442537442b2535432535432530412b2b2b2b25323636253742253543636f6c6f72253742677265656e253744253542322532433225324330253243312535442537442b2535432535432530412b2b2b2b25323637253742253543636f6c6f72253742726564253744253542332532433325324330253243322535442537442b2535432535432b2530412b2b2b2b25323638253742253543636f6c6f72253742726564253744253542332532433325324331253243322535442537442b2535432535432530412b2b2b2b25323639253742253543636f6c6f72253742726564253744253542342532433325324331253243322535442537442b2530412b2b2b2b253543656e64253742616c69676e65642537442530412b2b2b2b2535437269676874253544253543253543)
> 
> 建议close

好的
