### ISSUE TITLE
图片链接不支持仓库全局路径 ![alt](/images/blabla)

### ISSUE THREAD

**Issue by jingyibo123** [niudai/VSCode-Zhihu#145]
上传图片目前支持当前md文件同级目录下的相对图片路径，不支持仓库全局路径

示例目录结构：
```
  posts
    a.md
  images
    a.assets
      a1.png
```
在`a.md`中插入图片 `![](/images/a.assets/a1.png)` 上传时报错：

> 图片获取失败！
/images/a.assets/a1.png 图片获取异常，请调整链接再试！

**Comment by shouldsee** [comment]
`/images/a.assets/a1.png` 在操作系统里默认指向根目录下的`/images`文件夹. 请问"仓库全局路径"是在哪个语境下定义的呢? 仓库路径在不同的建站系统下有不同表述,一般会采用一些变量展开的办法. 目前最简单的办法是使用相对路径,或者直接把images挂载到根目录下作为一个symbolic link或者--bind

**Comment by w745784780** [comment]
问一下点击左侧链接不能查看文章是怎么回事，有遇到过吗

**Comment by shouldsee** [comment]
> 问一下点击左侧链接不能查看文章是怎么回事，有遇到过吗

我好像也看不了,只能刷新出一个列表,点不进去.估计要查log看哪里报错了

**Comment by jingyibo123** [comment]
> `/images/a.assets/a1.png` 在操作系统里默认指向根目录下的`/images`文件夹. 请问"仓库全局路径"是在哪个语境下定义的呢? 仓库路径在不同的建站系统下有不同表述,一般会采用一些变量展开的办法. 目前最简单的办法是使用相对路径,或者直接把images挂载到根目录下作为一个symbolic link或者--bind

我明白你的意思了。
仓库全局路径我是指当前所在git仓库，主要是参考了github的md渲染策略，对于这个拓展来讲可能确实不适用。

我来close吧。
