### ISSUE TITLE
关于知乎插件答案点不开的问题

### ISSUE THREAD

**Issue by niudai** [niudai/VSCode-Zhihu#148]
大家好！和大家好久不见了，我工作之后维护插件的时间少了很多，知乎目前的答案浏览 API 加了一些加密的校验逻辑，走正常的访问会报错，这就是为啥答案点不开，解决这个问题需要些时间（未必一定能解决），和大家解释一下...

**Comment by ghost** [comment]
加油,期待这个功能上线

**Comment by ZUIcat** [comment]
加油，用知乎的web编辑器简直想打人，这个插件发布文章真是丝般顺滑。

**Comment by YOLOtianmin** [comment]
加油相信大佬

**Comment by OnionGF** [comment]
差点卸载vscode 重装了。加油 期待早上回归

**Comment by JauSingSing** [comment]
这边有个知乎专栏说怎么加密，可以参考一下。我用Charles试了一下请求参数，似乎确实是 x-zse-96 这个请求头.
https://zhuanlan.zhihu.com/p/419576219

**Comment by niudai** [comment]
0.5.1 版本已经解决，close 了。

**Comment by niudai** [comment]
OK



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JauSingSing ***@***.***&gt;
发送时间: 2022年6月23日 17:09
收件人: niudai/VSCode-Zhihu ***@***.***&gt;
抄送: DaiNiu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [niudai/VSCode-Zhihu] 关于知乎插件答案点不开的问题 (Issue #148)






这边有个知乎专栏说怎么加密，可以参考一下。我用Charles试了一下请求参数，似乎确实是 x-zse-96 这个请求头.
https://zhuanlan.zhihu.com/p/419576219

**Comment by AnshanSniper** [comment]
现在好像又有这个问题了，VSCode版本1.75.0，2023年2月3日

**Comment by mimizao** [comment]
> 

是的，期待大佬早日解决

**Comment by ylongw** [comment]
2023-02-14仍然有这个问题 undefine

**Comment by AnshanSniper** [comment]
VSCode 1.76.0版本已可以正常打开

**Comment by pumc-zhou** [comment]
![image](https://github.com/niudai/VSCode-Zhihu/assets/63772269/f8ee4d9d-3e68-47fa-9a6d-64aded64d6e7)
一直转圈，无法login in
