### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by Hugo-Zhu** [niudai/VSCode-Zhihu#149]
1. 点击登陆按钮没有反应
2. 输入`Zhihu: Login`命令报错: `命令"Zhihu: Login"导致错误 (Unexpected token _ in JSON at position 2203)`

**Comment by shouldsee** [comment]
你之前有没有装过类似插件呀?

**Comment by Hugo-Zhu** [comment]
之前没有装过，我安装老版本的插件可以正常登录了

**Comment by shouldsee** [comment]
> 之前没有装过，我安装老版本的插件可以正常登录了

那是不是可以记录一下两个插件版本看看

**Comment by niudai** [comment]
什么叫老版本? 没复现

**Comment by surika** [comment]
补充一点相关信息供参考~系统mac 11.5.2，vscode 1.72.1，安装插件最新版0.5.1时登录会显示“运行命令 zhihu.login 错误: Unexpected string in JSON at position 456。这可能是由提交 zhihu.login 的扩展引起的。”，各种操作也无法使用，安装0.5.0版本则一切正常。

这个插件创作体验真的比网页版知乎好用太多，感谢大佬辛勤付出*⸜( •ᴗ• )⸝*
