### ISSUE TITLE
代码块和图片显示有问题

### ISSUE THREAD

**Issue by jumploop** [niudai/VSCode-Zhihu#16]
你好，我用新版的知乎插件发布文章，本地预览和知乎网站上的结果不一致，图片无法显示，代码块也出问题了，请帮忙看下

**Comment by jumploop** [comment]
版本: 1.42.1 (user setup)
提交: c47d83b293181d9be64f27ff093689e8e7aed054
日期: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by niudai** [comment]
请出示无法显示图片的 markdown 图片链接

**Comment by jumploop** [comment]
![python](image\v2-ea05b3c2f691cd8ef28db8e25328f436_1200x500.jpg)

**Comment by jumploop** [comment]
![python](image\v2-ea05b3c2f691cd8ef28db8e25328f436_1200x500.jpg)

**Comment by jumploop** [comment]
“![python](image\v2-ea05b3c2f691cd8ef28db8e25328f436_1200x500.jpg)”

**Comment by jumploop** [comment]
图片问题解决了，是我的语法问题，现在就剩代码块问题了

**Comment by niudai** [comment]
代码块问题已经修复
