### ISSUE TITLE
无法点开帖子

### ISSUE THREAD

**Issue by AnshanSniper** [niudai/VSCode-Zhihu#170]
热榜随便一篇都点不开
错误信息：Cannot read properties of undefined (reading 'map')
VSCode版本1.75.0
2023年2月3日

**Comment by JinWuZhao** [comment]
我这也是，1.75.1版本，插件是安装在wsl2里的

**Comment by AnshanSniper** [comment]
VSCode 1.76.0版本已可以正常打开
