### ISSUE TITLE
markdown文档中注释的处理

### ISSUE THREAD

**Issue by ericluo** [niudai/VSCode-Zhihu#24]
在0.2.3版本中，不能正确的处理注释。例如下面的 `markdown` 注释中，**title** 和  **tags** 都会显示在正文中。

此外，还希望在文档注释中有 **title** 时，在发布是可以默认将 **title** 的内容作为文章的标题，不需要额外手动输入了。

感谢！

```markdown
---
title: vscode研究
tags: 技术
--
```

**Comment by niudai** [comment]
好的

**Comment by niudai** [comment]
我有个问题，你写的这个是 markdown 的注释吗？我查了一下markdown的注释语法，好像没有这样的，这样写在vscode里预览也能看到，说明应该是不符合markdown标准语法的，我印象里大家在markdown里注释好像直接是html的那种

**Comment by HPDell** [comment]
我也发现了这个问题。那个好像叫文档元数据，hexo等博客系统用这个来添加文章的一些属性，如标题、标签、分类、日期啥的。希望作者能在解析markdown文件的时候从里面提取title出来并把其他的去掉。

**Comment by ericluo** [comment]
在&nbsp;Github&nbsp;Pages等markdown文档格式中有这类元数据支持。实际使用中还是很方便的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "DaiNiu"<notifications@github.com&gt;; 
发送时间: 2020年4月6日(星期一) 中午12:09
收件人: "niudai/VSCode-Zhihu"<VSCode-Zhihu@noreply.github.com&gt;; 
抄送: "6318 罗婉月"<luo.wenbo@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [niudai/VSCode-Zhihu] markdown文档中注释的处理 (#24)





 
Closed #24.
