### ISSUE TITLE
如何修改已发布的文章？

### ISSUE THREAD

**Issue by ericluo** [niudai/VSCode-Zhihu#25]
现有功能点中没有发现如何获取自己已发布的文章列表，以及如何对已发布的文件进行修订并重新发布呢？

如果对已发布的md文件进行修改后再提交，是会重新发布一篇新的文章吗？

**Comment by niudai** [comment]
现有功能有啊，仔细看readme，和修改答案一个原理，链接扫描

**Comment by niudai** [comment]
![image](https://user-images.githubusercontent.com/44165182/76193953-16d8bd80-6220-11ea-846e-590a88a78c7a.png)

**Comment by ericluo** [comment]
这里功能我注意到了。不过我理解还是需要脱离vscode，通过web获取原来文章的url吧？

可以在vscode内，获取自己发布文章的列表，并得到每篇文章对应的url吗？

**Comment by niudai** [comment]
这个功能可以做  接下来的版本逐步解决
