### ISSUE TITLE
我第二次上传时无法自动生成链接哦！

### ISSUE THREAD

**Issue by modifMX** [niudai/VSCode-Zhihu#27]
我第二次上传时无法自动生成链接哦！ 一开始我以为我插件出现问题，第一张测试图片一直没有自动生成链接。 
之后我发现图片问题貌似上传过了导致的。
好像每次一张图片只能自动生成一次链接，这样编写文章不太方便。

**Comment by niudai** [comment]
把 markdown 源码贴到这里  并且详细描述插件和发布后的行为  谢谢

**Comment by niudai** [comment]
哦哦  我发现了  下个版本解决

**Comment by modifMX** [comment]
> 哦哦 我发现了 下个版本解决

谢谢大佬 ， md源码就很普通的文本。 

![image](https://user-images.githubusercontent.com/8953309/76400683-a9619400-63bb-11ea-8848-b32bfc832d0b.png)

![image](https://user-images.githubusercontent.com/8953309/76400733-c0a08180-63bb-11ea-8ca6-a48788cd230a.png)

这些是上传后的。 就提示成功其他啥都没有

**Comment by niudai** [comment]
已经解决
