### ISSUE TITLE
关于添加图片的问题

### ISSUE THREAD

**Issue by SuccessorOfPredecessor** [niudai/VSCode-Zhihu#32]
利用markdown自带方式引用的本地图片可以直接发表出来。
但是不能调整大小，因此我常常用 HTML的方式，有时还会配合居中的标签。这时候，文章就就会忽略掉这个图片。

**Comment by niudai** [comment]
当前版本只支持markdown链接的本地路径，html 的话现在插件不会自动处理，所以不行
