### ISSUE TITLE
内容发布特定问题的回答失败

### ISSUE THREAD

**Issue by fanhoodrex** [niudai/VSCode-Zhihu#33]
>  若你想在特定的问题下回答，或想修改自己的某个原有回答，就将问题/答案链接以 #! https://... 的格式放置于答案的第一行，发布时，插件会自动扫描识别，发布至相应的问题下，或修改原有的答案。

> 若插件没有在首行扫描到链接，则会询问创作者接下来的操作，你可以选择发布新文章，或从收藏夹中选取相应问题，发布至相应问题下：

**是按照插件文档的操作写的，首行是!#符号+问题链接**

```
!# https://www.zhihu.com/question/298691365
```
但是无法成功发布特定问题的回答，点击发布按钮后会变成询问创作者接下来的操作，选择发布新文章或从收藏夹中选取相应问题，发布至相应问题下。

不知道是不是我本人哪里的操作失误，如果开发者能做一个简短的教程视频录制操作就直观多了

**Comment by niudai** [comment]
应该是 #! 而不是 !#

**Comment by fanhoodrex** [comment]
诶呀，没有认真仔细看文档，打扰开发者咯
