### ISSUE TITLE
建议增加视频/gif上传功能

### ISSUE THREAD

**Issue by ZgblKylin** [niudai/VSCode-Zhihu#34]
markdown可以通过html tag方式插入视频，在GitHub等在线平台上无法正确播放，但使用typora等浏览工具可以识别并播放。

中文博客推荐的是用iframe标签添加视频/gif，但实测typora不支持。

另一种写法是用video标签，在typora中可正确播放，只是其中的样式属性无法生效，如：
```html
<video autoplay="" muted="" loop=""><source src="https://update.tabnine.com/v/cpp_demo_1.mp4" type="video/mp4"></video>
```

建议文章上传时，可以检查是否有video标签，若有，则从source.src中提取视频url进行上传。

另外，据说iframe可以用于播放，我没有试过，若typora等编辑器支持的话，可考虑上传时提取图片路径后，按图片上传流程提交。

**Comment by niudai** [comment]
gif 本来就支持，你可以试一下，视频的话其实以后可以加，但是就算加了也没办法在 VSCode 里预览播放，因为 VSCode 内部不支持视频播放

**Comment by liuxilu** [comment]
为什么不支持视频播放？CSP？

**Comment by gricn** [comment]
> gif 本来就支持，你可以试一下，视频的话其实以后可以加，但是就算加了也没办法在 VSCode 里预览播放，因为 VSCode 内部不支持视频播放

还是希望岱哥能支持一下，增加视频功能可以避免跑去知乎二次编辑
