### ISSUE TITLE
不要默认globally启用

### ISSUE THREAD

**Issue by jindongwang** [niudai/VSCode-Zhihu#41]
感谢大佬的贡献！
提2个小小的建议：
1. 不要默认globally启用，可以在点击知乎图标后再启用；
2. 与上一条对应，如果默认是全局启用，可能会占额外网速和性能，并且日常写markdown时，右上角总是会有知乎的2个按钮在，很容易点错。

**Comment by niudai** [comment]
好的我考虑一下
