### ISSUE TITLE
关于登录方式问题

### ISSUE THREAD

**Issue by my-vegatable-has-exploded** [niudai/VSCode-Zhihu#42]
更新后好像只能使用二维码登录，不太方便。

**Comment by niudai** [comment]
账密登录现在有点问题  暂时关闭了  等功能正常了会重新启用  其它的登陆方式也在开发中

**Comment by my-vegatable-has-exploded** [comment]
> 账密登录现在有点问题 暂时关闭了 等功能正常了会重新启用 其它的登陆方式也在开发中

明白了，感谢。
