### ISSUE TITLE
登陆的时候提示：Unexpected token x in JSON at position 256 

### ISSUE THREAD

**Issue by Arctanxy** [niudai/VSCode-Zhihu#45]
如题，安装vscode-zhihu之后，使用Ctrl+Shift+P，选择Login。

vscode右下角弹出提示：Unexpected token x in JSON at position 256 

想请教一下大佬，如何解决这个问题？

**Comment by niudai** [comment]
具体情况我再看看&nbsp; 现在还不知道原因




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dai Liang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 下午4:30
收件人:&nbsp;"niudai/VSCode-Zhihu"<VSCode-Zhihu@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[niudai/VSCode-Zhihu] 登陆的时候提示：Unexpected token x in JSON at position 256  (#45)





 
如题，安装vscode-zhihu之后，使用Ctrl+Shift+P，选择Login。
 
vscode右下角弹出提示：Unexpected token x in JSON at position 256
 
想请教一下大佬，如何解决这个问题？

**Comment by Arctanxy** [comment]
> 具体情况我再看看&nbsp; 现在还不知道原因
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Dai Liang"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月21日(星期二) 下午4:30 收件人:&nbsp;"niudai/VSCode-Zhihu"<VSCode-Zhihu@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[niudai/VSCode-Zhihu] 登陆的时候提示：Unexpected token x in JSON at position 256 (#45) 如题，安装vscode-zhihu之后，使用Ctrl+Shift+P，选择Login。 vscode右下角弹出提示：Unexpected token x in JSON at position 256 想请教一下大佬，如何解决这个问题？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，谢谢大佬， 需要我这边提供什么信息吗？

**Comment by niudai** [comment]
你的电脑是 mac 还是 windows？

**Comment by niudai** [comment]
你先使用 logout 命令注销，再登陆试试

**Comment by Arctanxy** [comment]
> 你的电脑是 mac 还是 windows？

是windows，后来重新安装一次就好了，谢谢啦

**Comment by FeixiangChu** [comment]
我也遇到一样的问题，重装后也没有解决

**Comment by FeixiangChu** [comment]
mac重装后解决
