### ISSUE TITLE
上传至草稿

### ISSUE THREAD

**Issue by liuxilu** [niudai/VSCode-Zhihu#49]
在知乎上预览

**Comment by niudai** [comment]
下个版本实现

**Comment by liuxilu** [comment]
一般不是实现后再关吗…………

**Comment by zhaoqingqing** [comment]
看来要自己实现了，我也想问下这个功能。
我还想问一下定时发布的原理是啥？现在定时发布只能选当天，不能跨天

**Comment by niudai** [comment]
最近没时间维护这个项目了，等有时间的时候我会替你们看的哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: qingqing.zhao ***@***.***&gt;
发送时间: 2021年6月6日 22:37
收件人: niudai/VSCode-Zhihu ***@***.***&gt;
抄送: DaiNiu ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[niudai/VSCode-Zhihu] 上传至草稿 (#49)

**Comment by zhaoqingqing** [comment]
> 最近没时间维护这个项目了，等有时间的时候我会替你们看的哈 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: qingqing.zhao ***@***.***&gt; 发送时间: 2021年6月6日 22:37 收件人: niudai/VSCode-Zhihu ***@***.***&gt; 抄送: DaiNiu ***@***.***&gt;, State change ***@***.***&gt; 主题: 回复：[niudai/VSCode-Zhihu] 上传至草稿 (#49)

OK，我有空的时候也看看源码，看能不能自己先改着用。
