### ISSUE TITLE
文章发布中

### ISSUE THREAD

**Issue by Gemini-Lin** [niudai/VSCode-Zhihu#51]
当我在插件上点击发布文章后，文章一直显示“文章发布中”，但是半天都没有发布出去。
![t1urC9.png](https://s1.ax1x.com/2020/05/31/t1urC9.png)

**Comment by Gemini-Lin** [comment]
经过排查，我发现原因是发布文章的内容可能是超过了知乎的字数限制。
因为我发布内容较少的文章时是可以直接发送的，
当发布内容较多的文章时就会一直卡在文章发布中。

**Comment by niudai** [comment]
嗯嗯  应该是
