### ISSUE TITLE
发表文章的时候能不显示“使用zhihu插件创作发布”吗？

### ISSUE THREAD

**Issue by BowenXiao1999** [niudai/VSCode-Zhihu#56]
^ 主要原因是，在文章未完全点开的时候，这一段会占据很多空间，影响阅读体验。

**Comment by zhaoqingqing** [comment]
现在这个版本的小尾巴，是放在文章的开头，确实影响体验。
我正在尝试下载源码自己重新编译一个版本，建议作者写一个详细些的build和在vscode上debug指南，现在CONTRIBUTING.md中的有些太简单的，我去了解下这块知识。
@liuxilu

**Comment by zhaoqingqing** [comment]
我已经按照自己的需求，通过源代码重新编译了一个扩展，解决了这个问题。
![image](https://user-images.githubusercontent.com/3056814/119959021-2e8f9380-bfd6-11eb-9acd-ef9a7ddf33c7.png)

@BowenXiao1999

**Comment by liuxilu** [comment]
我是直接到安装目录改的，VSIX应该也能直接改。
其实那个PR我也没编译过；看来竟然还没release？
~~小尾巴长在头上XD~~

**Comment by zhaoqingqing** [comment]
我从vscode扩展中心下载的是带这个小尾巴的，而且是在文章在首行，首字。然后我昨天就自己clone 源码，修改后编译了自己用。
感谢作者的开源。

**Comment by niudai** [comment]
已经放到文末了哈，帮作者宣传下
