### ISSUE TITLE
知乎 0.2 版本 Feature

### ISSUE THREAD

**Issue by niudai** [niudai/VSCode-Zhihu#6]
>该 issue 根据用户们征集的意见，对 0.2 版本将加入的新功能做一个草拟, 会随着用户的反馈不断变化, 并在实际的开发中付诸实施。✅ 表示已经实现。

1. 内容定时发布功能 ✅
2. 可以从 Webview 中提取问题/答案/文章 的链接。✅
3. CSS样式跟随VSCode主题。✅
4. 取消宏刷新，刷新按钮作用到特定的 Treeview 上。✅

**Comment by KKSun** [comment]
能把.vscode文件夹也放到repo里吗，这样方便fork之后调试
