### ISSUE TITLE
VScode npm run compile出错

### ISSUE THREAD

**Issue by PhDLuffy** [niudai/VSCode-Zhihu#60]
大神您好：

我在Mac下编译发现出错通不过，显示context有问题

![github-zhihuVScode](https://raw.githubusercontent.com/PhDLuffy/PicGo/master/img/20200622161705.png)

这部分里面有个cookie.json文件，我看仓库里没有，你再gitignore里给去除了

![github-zhihuVScode2](https://raw.githubusercontent.com/PhDLuffy/PicGo/master/img/20200622161747.png)

还有一处就是context.json这里，我把路径改成自己的路径，不知道这样改对不对？

![github-zhihuVScode3](https://raw.githubusercontent.com/PhDLuffy/PicGo/master/img/20200622161919.png)

**Comment by niudai** [comment]
你运行的是测试的那个task吧，在launch.json中还有一个webpack启动的task，用那个，现在测试基本不管了



---原始邮件---
发件人: "PhDLuffy"<notifications@github.com&gt;
发送时间: 2020年6月22日(周一) 晚上11:23
收件人: "niudai/VSCode-Zhihu"<VSCode-Zhihu@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [niudai/VSCode-Zhihu] VScode npm run compile出错 (#60)




 
大神您好：
 
我在Mac下编译发现出错通不过，显示context有问题
 

 
这部分里面有个cookie.json文件，我看仓库里没有，你再gitignore里给去除了
 

 
还有一处就是context.json这里，我把路径改成自己的路径，不知道这样改对不对？

**Comment by PhDLuffy** [comment]
谢谢大神回复，已解决。
