### ISSUE TITLE
选项不显示“本文使用 Zhihu On VSCode 创作并发布”

### ISSUE THREAD

**Issue by wangzhe3224** [niudai/VSCode-Zhihu#77]
谢谢作者开发。

我理解作者希望可以宣传，但是最好还是留给大家自由选择的权利？

**Comment by my-vegatable-has-exploded** [comment]
同建议。

**Comment by joshion** [comment]
虽然在插件中的extension.js中；删除以下语句就可以达成目的。
`a&&(i=i.slice(i.indexOf("\n")+1)),i=">本文使用 [Zhihu On VSCode](https://zhuanlan.zhihu.com/p/106057556) 创作并发布\n\n"+i;`
但是希望作者来提供这种选项选择。

甚至于，可以链接到 https://github.com/niudai/VSCode-Zhihu， 而不是https://zhuanlan.zhihu.com/p/106057556。

**Comment by niudai** [comment]
Ok 完了搞下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zhe Wang ***@***.***&gt;
发送时间: 2020年11月11日 05:50
收件人: niudai/VSCode-Zhihu ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[niudai/VSCode-Zhihu] 选项不显示“本文使用 Zhihu On VSCode 创作并发布” (#77)






谢谢作者开发。

我理解作者希望可以宣传，但是最好还是留给大家自由选择的权利？

**Comment by niudai** [comment]
现在已经放在文末了，这个先关啦
