### ISSUE TITLE
公式编辑预览重复

### ISSUE THREAD

**Issue by zdxiao** [niudai/VSCode-Zhihu#8]
![image](https://user-images.githubusercontent.com/9161231/74581381-e1a6ca00-4fe9-11ea-80f5-d4582530d66c.png)
如上截图，公式编辑预览有问题，发生重复。

环境：MacBook Pro

**Comment by niudai** [comment]
这个是你写错了，一个美元符号包裹的叫行内 latex，不要换行，直接 $\beta=\alpha$ 就行，这也是最新版本刚实现的 feature
上面那个引用的问题，实际上应该是你写错了，markdown的语法应该中间空一行

**Comment by zdxiao** [comment]
> 这个是你写错了，一个美元符号包裹的叫行内 latex，不要换行，直接 $\beta=\alpha$ 就行，这也是最新版本刚实现的 feature
> 第二个重复问题，不知道为什么我这边测试的是正常的，你看看你有没有安装 Markdown All In One 这个插件，没有的话安装一下
> 上面那个引用的问题，实际上应该是你写错了，markdown的语法应该中间空一行

感谢，重复的问题安装“Markdown All In One”后解决。
