### ISSUE TITLE
图片获取异常，请调整链接再试！

### ISSUE THREAD

**Issue by zjs1224522500** [niudai/VSCode-Zhihu#80]
使用自建图床，报错信息如下。但预览都是 OK 的
![image](https://user-images.githubusercontent.com/17877010/100896548-b0a47100-34f9-11eb-9661-37d6eb1f3d7c.png)

**Comment by niudai** [comment]
自建图床是啥意思, 插件默认使用的是知乎的图床, 你的图片的路径中是有中文吗还是
